name: CI/CD Django App

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias del sistema (Pillow)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libjpeg-dev \
            zlib1g-dev \
            libpng-dev

      - name: Instalar dependencias Python
        run: |
          cd app
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          

      - name: Snyk - Análisis de seguridad de dependencias
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=requirements.txt
        continue-on-error: true


      - name: Django check
        run: |
          cd app
          python manage.py check

      - name: Ejecutar migraciones (dry-run)
        run: |
          cd app
          python manage.py makemigrations --check --dry-run

      - name: Ejecutar tests
        run: |
          cd app
          python manage.py test --verbosity=2
        continue-on-error: true

      - name: Build Docker image
        run: |
          cd app
          docker build -t django-app:latest .
